### ISSUE TITLE
Enhance the acnode logging laser run time setup

### ISSUE THREAD

**Issue by deanforbes** [londonhackspace/lightburn#6]

**Comment by zymurgic** [comment]
It's probably worthwhile adding some RC input filtering to the acnode tool running input. Any frequency above 1Hz needs filtering.

**Comment by deanforbes** [comment]
It could work, do you have what you need to try it. If that fails, I would suggest looking at a mechanical relay driven by the current sensor which could provide isolation and a high/low signal which could be fed to the acnode.  

For the final solution one board could be made to host this (either the RC filter or relay setup) and the level shifter if we deem it necessary

**Comment by zymurgic** [comment]
That's exactly what we have at the moment. The current sensor drives a relay on the same module, and we use that to trigger a switch input to pull an input line to ground. Of course, like any switch, it could do with debouncing, and I'd prefer to do that in hardware rather than software.

**Comment by deanforbes** [comment]
hardware is my preference so that is good 
If we have that level of isolation I am lost as to why we are still having a problem 
I will wait till the next round of investigation has been done ..

**Comment by deanforbes** [comment]
done
